sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t nanda1995/react-test -f ./client/Dockerfile.dev ./client

script:
  # - docker run nanda1995/react-test npm test -- --coverage
  - docker run -e CI=true nanda1995/react-test npm test

after_success:
    - docker build -t nanda1995/multi-client ./client
    - docker build -t nanda1995/multi-nginx ./nginx
    - docker build -t nanda1995/multi-server ./server
    - docker build -t nanda1995/multi-worker ./worker
    # - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    # - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    - docker push nanda1995/multi-client
    - docker push nanda1995/multi-nginx
    - docker push nanda1995/multi-server
    - docker push nanda1995/multi-worker
